### ISSUE TITLE
vite-tsconfig-paths cannot import a basic TSconfig extends in sub-folder

### ISSUE THREAD

**Issue by matthew-dean** [aleclarson/vite-tsconfig-paths#150]
I've reduced the test case to this: https://stackblitz.com/edit/vitest-dev-vitest-oip9io?initialPath=__vitest__/

You can see that this Vite plugin fails entirely to resolve paths using TSConfig settings.

It's important to note that:
1. The app itself and TypeScript compiler work fine with this setup. Paths are always relative to their `tsconfig.json` file, but vite-tsconfig-paths does not account for that, and incorrectly merges path options.
2. In my actual use case, I do not have control over extending from a sub-folder nor the paths. They are auto-generated by [Nuxt](https://nuxt.com/).

**Comment by juni0r** [comment]
@matthew-dean Did you find a fix?

**Comment by aleclarson** [comment]
In the case of @matthew-dean's reproduction, the fix is to set `baseUrl` in the `.config/tsconfig.json` file to `../` and replace the `../` prefixes in the `paths` array with `./` prefixes.

#### Example `.config/tsconfig.json` file

```tsconfig.json
{
  "compilerOptions": {
    "target": "es2020",
    "module": "node16",
    "moduleResolution": "Node16",
    "strict": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "verbatimModuleSyntax": true,
    "baseUrl": "../",
    "paths": {
      "~": ["./src"],
      "~/*": ["./src/*"]
    }
  },
  "include": ["../src", "../test"],
  "exclude": ["../node_modules"]
}
```

This has an unfortunate side effect of allowing `src/basic.js` as an import specifier, due to how the `baseUrl` option works.

The ideal solution is for someone to contribute a fix to [tsconfck](https://github.com/dominikg/tsconfck) that rebases `paths` inherited from an extended tsconfig (see [here](https://github.com/dominikg/tsconfck/blob/dcc0904ed2720e49267ae4c767ca1e43cf98be3b/packages/tsconfck/src/parse.js#L325) for relevant code).

**Comment by aleclarson** [comment]
I've submitted a fix to `tsconfck`

https://github.com/dominikg/tsconfck/pull/206

**Comment by aleclarson** [comment]
Fixed in v5.1.4

**Comment by mamunonweb** [comment]
![image](https://github.com/user-attachments/assets/345bb9b1-57dd-486c-8799-df44ba027575)

I still can't make it work!

**Comment by aleclarson** [comment]
Hi @mamunonweb, that's not related to this issue. Try reproducing your issue in the test suite by tweaking the [paths-outside-root](https://github.com/aleclarson/vite-tsconfig-paths/tree/master/test/__fixtures__/paths-outside-root) test fixture and until it fails. You can run the test with this command:
```
pnpm vitest -t paths-outside-root
```
