### ISSUE TITLE
Path options do not work with `vitest` `vi.mock`

### ISSUE THREAD

**Issue by haakonjackfloat** [aleclarson/vite-tsconfig-paths#99]
Given a `tsconfig.json` like so: 

```json
{
  "compilerOptions": {
    "baseUrl": "./app",
    "paths": {
      "@c/*": ["../../common/src/*"],
    }
  },
  "include": ["app/**/*"],
}
```

And a `vite.config.ts`: 

```ts
import path from 'path';
import { defineConfig } from 'vitest/config';
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig({
  test: {
    globals: true,
    setupFiles: path.resolve(__dirname, 'testSetup'),
  },
  plugins: [tsconfigPaths() as any],
});
```

In a `vitest` spec file: 

```ts
import { someMethod } from '@c/some/lib';

// This does not work, `someMethod` will not be a spy
vi.mock('@c/some/lib', () => {
  return {
    someMethod: vi.fn(),
  };
});

// This does work
vi.mock('../../common/src/some/lib', () => {
  return {
    someMethod: vi.fn(),
  };
});

```

**Comment by tb-viktor** [comment]
Encountering this problem as well.

In our case we don't have any specific paths declared in our `tsconfig`, but just use the `tsconfigPaths()` plugin to shorten import paths from the base url. As above, `vi.mock` does not resolve it properly. When we change the mock path from e.g. `folder1/folder2/file` to `/baseUrl/folder1/folder2/file` explicitly it works, but it is not ideal and makes migration from `jest` somewhat tedious with a large amount of test files.

**Comment by DanHulton** [comment]
This may be related...  I have `vite-tsconfig-paths` set up nearly exactly the same as above (js file for vite.config, but otherwise the same), and I have been unable to get dynamic imports to work when running vitest.

`import { configurePassport } from '#api/Passport';` works, but `const { configurePassport} = import('#api/Passport');` will not, with the error `Error: Failed to load url #api/Passport (resolved id: #api/Passport). Does the file exist?`

These imports work just fine when running the app via `vite-node`, it's just in `vitest` that they no longer resolve.

Potentially the same code path doing the resolving for dynamic imports as trying to resolve mocks?  I haven't seen much discussion of vitest resolution issues outside of this specific issue.

**Comment by cayter** [comment]
It's a vitest [bug](https://github.com/vitest-dev/vitest/issues/2775) and they just reverted the commit in v0.28.4 about an hour ago.

**Comment by DanHulton** [comment]
TYVM, @cayter!  It turns it these two were related.  Updated to vitest 0.28.4 and the issue with dynamic imports is fixed as well!

**Comment by haakonjackfloat** [comment]
Indeed, looks fixed! Thanks for the heads up @cayter!
